# print("hon \n itent")
# print('The Flhtsn,"tru"')
# print("\"ni\"l")
# a= (input())
# print(type(a))
# print(ord(a))
# print(chr(65))
name=input("name:")
age=input('age:')
gender=input('gender:')
height=input('height:')
print(name)
print(age)
print(gender)
